# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Матері його ковінька
email: vipyvo@microsoft.com
description: > # this means to ignore newlines until "baseurl:" 
  Interesing stuff for interesting people on behalf of materi yogo kovinka.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://emettant.github.io" # the base hostname & protocol for your site
twitter_username: vpyvovar
github_username:  emettant

# Build settings
markdown: kramdown

#default
site_url: http://emettant.github.io/
