# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Агов
email: vipyvo@microsoft.com
description: > # this means to ignore newlines until "baseurl:" 
  This is an awesome description for this site here. It might be even better description in the third sentence. Yet, not the best but already event better description. I hope google indexate this awesomely too. SQL Azure, .NET, music, latin dances, politics another interesing stuff from interesting people.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://emettant.github.io" # the base hostname & protocol for your site
twitter_username: vpyvovar
github_username:  emettant

# Build settings
markdown: kramdown
